---
title: "Western U.S. Water Rights"
author: "Natalie Mayer"
format: html
editor: visual
---
# Data Wrangling 

## Load data and libraries
```{r}
#| eval: true
#| warning: false
#| message: false
#| code-fold: true


library(tidyverse)
library(here)

arizona <- read_csv(here("data", "arizona.csv"))
california <- read_csv(here("data", "california.csv"))
colorado <- read_csv(here("data", "colorado.csv"))
idaho <- read_csv(here("data", "idaho.csv"))
montana <- read_csv(here("data", "montana.csv"))
nevada <- read_csv(here("data", "nevada.csv"))
new_mexico <- read_csv(here("data", "new_mexico.csv"))
oregon <- read_csv(here("data", "oregon.csv"))
utah <- read_csv(here("data", "utah.csv"))
washington <- read_csv(here("data", "washington.csv"))
wyoming <- read_csv(here("data", "wyoming.csv"))
```

## Reclassify variable types and add legal framework column from ESM 225: Water Policy Lecture Notes and Readings
```{r}
#| eval: true
#| warning: false
#| message: false
#| code-fold: true


az <- arizona %>%
  mutate(legal_framework = "Prior Appropriation (But 40% of water comes from the Colorado River under a different system)") %>%
  mutate(waterRightID = factor(waterRightID),
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         surBasinNum = factor(surBasinNum), 
         grdBasinNum = factor(grdBasinNum))

ca <- california %>%
  mutate(legal_framework = "Hybrid: Riparian (Pre-1914) & Prior Appropriation (Post-1914)") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

co <- colorado %>%
  mutate(legal_framework = "Prior Appropriation (Issued and adjudicated by Water Courts)") %>%
  mutate(waterRightID = factor(waterRightID),
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

id <- idaho %>%
  mutate(legal_framework = "Prior Appropriation and Basin Management Agencies") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

mt <- montana %>%
  mutate(legal_framework = "Prior Appropriation (Adjudicated by State Water Court)") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

nv <- nevada %>%
  mutate(legal_framework = "Prior Appropriation (Administered by State Engineer/Division of Water Rights)") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

nm <- new_mexico %>%
  mutate(legal_framework = "Prior Appropriation (Administered by State Engineer/Division of Water Rights)") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

or <- oregon %>%
  mutate(legal_framework = "Prior Appropriation (Strict 5 year 'use-it-or-lose-it' window)") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

ut <- utah %>%
  mutate(legal_framework = "Prior Appropriation (Administered by State Engineer/Division of Water Rights)") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

wa <- washington %>%
  mutate(legal_framework = "Prior Appropriation and Water Resource Inventory Areas") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))

wy <- wyoming %>%
  mutate(legal_framework = "Prior Appropriation (Administered by State Engineer/Division of Water Rights)") %>%
  mutate(waterRightID = factor(waterRightID), 
         FIPS = factor(FIPS), 
         priorityDate = as.Date(priorityDate, format = "%m/%d/%y"), 
         origWaterUse = factor(origWaterUse), 
         basinNum = factor(basinNum))
```

## Join data for all western states
```{r}
#| eval: true
#| warning: false
#| message: false
#| code-fold: true


western_states <- bind_rows(az, ca, co, id, mt, nv, nm, or, ut, wa, wy)
```

# Exploratory Data Analysis 

## How have water rights changed over time in CA? 

```{r}
#| eval: true
#| warning: false
#| message: false
#| code-fold: true


library(stringr)

ca_wr <- ca %>%
  group_by(origWaterUse, waterUse) %>%
  summarise(cfs = sum(CFS)) %>%
  ungroup() %>%
  mutate(waterUse = str_to_title(waterUse))

library(networkD3)

# create links data frame
links <- data.frame(ca_wr) %>%
  mutate(source = origWaterUse, 
         target = waterUse, 
         value = cfs)

# create node data frame
nodes <- data.frame(
  name=c(as.character(links$source), 
  as.character(links$target)) %>% unique()
)

# reformat nodes so connection can be made using id
links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1

# make the network 
p <- sankeyNetwork(Links = links, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              sinksRight=FALSE)
p

```

## How do Water Rights in CA compare to other Western States? 

```{r}
#| eval: true
#| warning: false
#| message: false
#| code-fold: true

ws <- western_states %>%
  group_by(state, waterUse) %>%
  summarise(cfs = sum(CFS)) %>%
  ungroup() %>%
  drop_na()

ggplot(data = ws, aes(x = waterUse, y = cfs)) + 
  geom_col() + 
  coord_flip() +
  facet_wrap(~state, scales = "free_x") + 
  theme(axis.text.x = element_text(angle = 45)) 
```






































